[project]
name = "chatgpt-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "minsearch",
    "pandas",
]

[project.scripts]
dev = "main:dev"
